name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Poetry Setup
        run: pip install poetry && poetry config virtualenvs.create false && poetry self add poetry-dotenv-plugin && poetry install --no-interaction --with test && mv .env.cicd .env

      - name: Lint
        run: poetry run lint

      - name: Test
        run: poetry run test

  dependency-scanning:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.3.3"
    needs: test

  SAST:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize SAST
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Build SAST
        uses: github/codeql-action/autobuild@v3

      - name: Run SAST
        uses: github/codeql-action/analyze@v3
  
  secret-scanning:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Secret Scanning
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - dependency-scanning
      - SAST
      - secret-scanning
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"